In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("Stock.csv")
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
#numpy
X_raw=dataset.iloc[:, :-1].values
Y_raw=dataset.iloc[:,-1].values

In [4]:
#pandas
datasetX_raw=dataset.iloc[:, :-1]
seriesY_rawdatasetX=dataset.iloc[:,-1]

In [5]:
datasetX=datasetX_raw.copy()
seriesY=seriesY_rawdatasetX.copy()
datasetX.info()
seriesY.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  10 non-null     str
 1   Age      9 non-null      float64
 2   Salary   9 non-null      float64
dtypes: float64(2), str(1)
memory usage: 432.0 bytes
<class 'pandas.Series'>
RangeIndex: 10 entries, 0 to 9
Series name: Purchased
Non-Null Count  Dtype
--------------  -----
10 non-null     str
dtypes: str(1)
memory usage: 237.0 bytes

In [6]:
print(datasetX_raw.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  10 non-null     str
 1   Age      9 non-null      float64
 2   Salary   9 non-null      float64
dtypes: float64(2), str(1)
memory usage: 432.0 bytes
None

In [7]:
X_raw=pd.DataFrame(X_raw)
X_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       10 non-null     str
 1   1       9 non-null      object
 2   2       9 non-null      object
dtypes: object(2), str(1)
memory usage: 432.0+ bytes

In [8]:
X_raw=X_raw.values
X_raw

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [9]:
#counting no of null values
print(datasetX.isnull().sum())

Country    0
Age        1
Salary     1
dtype: int64

In [10]:
#counting no of null values
print(X_raw.isnull().sum())

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'

In [11]:
datasetX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [12]:
datasetX_raw=datasetX_raw.fillna(0)
datasetX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [13]:
datasetX_raw=datasetX_raw.replace(0,np.nan)
datasetX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [14]:
ind=datasetX_raw.columns.get_loc('Age') #get the specific location
ind

1

In [ ]:
#filling the missing values with constant for a specific coloumn
datasetX_raw.iloc[:,1]=datasetX_raw.iloc[:,1].fillna(5)
datasetX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   5.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [15]:
#get the old data back
datasetX_raw=datasetX_raw.copy()
datasetX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [16]:
datasetX_raw

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [17]:
#simpleimputer is a class used to handle missing values with simple strategies
datasetX_raw=datasetX_raw.copy()
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
datasetX_raw.iloc[:,1:3]=imputer.fit_transform(datasetX_raw.iloc[:,1:3])
datasetX_raw

   Country        Age        Salary
0   France  44.000000  72000.000000
1    Spain  27.000000  48000.000000
2  Germany  30.000000  54000.000000
3    Spain  38.000000  61000.000000
4  Germany  40.000000  63777.777778
5   France  35.000000  58000.000000
6    Spain  38.777778  52000.000000
7   France  48.000000  79000.000000
8  Germany  50.000000  83000.000000
9   France  37.000000  67000.000000

In [18]:
dataset = pd.read_csv('Stock.csv')
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [19]:
#get the old data back
datasetX_raw=dataset.copy()
datasetX_raw

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [21]:
#replace with constant values
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='constant', fill_value=5)
imputer.fit(datasetX_raw.iloc[:,1:3])
datasetX_raw.iloc[:, 1:3] = imputer.transform(datasetX_raw.iloc[:, 1:3])
datasetX_raw

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      5.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   5.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [22]:
X_raw=X_raw.copy()
X_raw

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [23]:
X1=X_raw.copy()
X1

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [24]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
X1[:,1:3]=imputer.fit_transform(X1[:,1:3])
X1

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [25]:
X_raw

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [26]:
d1=datasetX_raw.copy()
d1

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      5.0       Yes
5   France  35.0  58000.0       Yes
6    Spain   5.0  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [27]:
X_raw

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [28]:
d1=pd.get_dummies(d1,columns=['Country'])  #onehotencoding
d1

    Age   Salary Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0        No            True            False          False
1  27.0  48000.0       Yes           False            False           True
2  30.0  54000.0        No           False             True          False
3  38.0  61000.0        No           False            False           True
4  40.0      5.0       Yes           False             True          False
5  35.0  58000.0       Yes            True            False          False
6   5.0  52000.0        No           False            False           True
7  48.0  79000.0       Yes            True            False          False
8  50.0  83000.0        No           False             True          False
9  37.0  67000.0       Yes            True            False          False

In [29]:
datasetX_raw=dataset.copy()
datasetX_raw

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
X=X_raw.copy()
X=pd.get_dummies(X1,columns=['Country'])
X  #doesnt work on numpy array

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

In [ ]:
from sklearn.compose import ColumnTransformer   # Applies different transformations to specific columns in a dataset simultaneously.
from sklearn.preprocessing import OneHotEncoder # Converts categorical categories into binary (0/1) columns for machine learning models.

# ct = ColumnTransformer(transformers=[('encoder', 'drop', [0])], remainder='passthrough')
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
X = np.array(ct.fit_transform(X))

In [32]:
from sklearn.preprocessing import LabelEncoder  #It is use to convert categorical target labels into numerical labels
le = LabelEncoder()
y = le.fit_transform(Y_raw)
print(y)

[0 1 0 0 1 1 0 1 0 1]

In [33]:
print(le.fit_transform(["india", "paris", "tokyo", "amsterdam"]))

[1 2 3 0]

In [ ]:
print(dataset)
print()
print(X_raw)
print()
print(Y_raw)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']

In [35]:
from sklearn.model_selection import train_test_split   #Splits the dataset into separate training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(
    np.asarray(X_raw), 
    np.asarray(Y_raw),  
    test_size=0.2, 
    random_state=1
)   #here, 80% train / 20% test to train and evaluate the model on unseen data.

In [36]:
print(X_train)

[['Spain' nan 52000.0]
 ['Germany' 40.0 nan]
 ['France' 44.0 72000.0]
 ['Spain' 38.0 61000.0]
 ['Spain' 27.0 48000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 35.0 58000.0]]

In [37]:
print(X_test)

[['Germany' 30.0 54000.0]
 ['France' 37.0 67000.0]]

In [38]:
#Standard scaler is applied on the features having numerical values and the formula is 
#z = (x - u) / s  or (x - u) / sigma where z is standardized and scaled value of x

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 1:] = sc.fit_transform(X_train[:, 1:])
X_test[:, 1:] = sc.transform(X_test[:, 1:])

In [39]:
print(X_train)
print()
print(X_test)

[['Spain' nan -1.0182239953527132]
 ['Germany' -0.038910211282047996 nan]
 ['France' 0.5058327466666259 0.583476671494251]
 ['Spain' -0.3112816902563849 -0.2974586952715793]
 ['Spain' -1.809324824615238 -1.3385641287221062]
 ['France' 1.0505757046152997 1.1440719048906884]
 ['Germany' 1.3229471835896367 1.4644120382600814]
 ['France' -0.7198389087178904 -0.537713795298624]]

[['Germany' -1.4007676061537326 -0.8580539286680168]
 ['France' -0.4474674297435534 0.18305150478250995]]